version: '3.5'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sample_rails_rest_api_test
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./coverage:/app/coverage
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  db_data:
