version: '3.5'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rm tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0
    volumes:
      - ./coverage:/app/coverage
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    env_file:
      - .env

volumes:
  db_data:
