development:
  adapter: postgresql
  host: postgres
  encoding: unicode
  pool: 10
  username: postgres
  database: sample_rails_rest_api_development
  password: postgres
test:
  adapter: postgresql
  host: postgres
  encoding: unicode
  pool: 10
  username: postgres
  database: sample_rails_rest_api_test<%= ENV['TEST_ENV_NUMBER'] %>
  password: postgres
